### ISSUE TITLE
Tutorial for a Lightweight Docker Swarm Environment

### ISSUE THREAD

**Issue by rsoika** [swarmpit/swarmpit#184]
Hi,
I have written a short tutorial how to setup a Lightweight Docker Swarm Environment with swarmpit.io as the Front-End UI. 
https://ralph.blog.imixs.com/2017/11/27/lightweight-docker-swarm-environment/
I don't know, but maybe it can help in some way.... 

At this point I would like to express my gratitude for your great work! Thanks a lot!

**Comment by nohaapav** [comment]
@rsoika Hi Ralph, thank you very much. We we're speaking about tutorial for a long time but still busy with something so we really appreciate that. If you don't mind we will use this reference in our twitter acc & other media as well.

Cheers

**Comment by rsoika** [comment]
That's ok for me. You are welcome. 

Ralph

**Comment by matthiasbaldi** [comment]
Thank you for the good manual, I miss one important point.
For a productive env, what for security and protection mechanisms should we use.
Because over a reverse proxy you can protect very well the pages and containers but the swarmpit UI is exposed to the internet.
As I know swarmpit does not support a two factor auth, so it have to be behind the proxy to allow an additional authentication.
I'm not a professional with traefik, so maybe I didn't saw an important thing.
What do you think?

**Comment by rsoika** [comment]
hm..., the build-in security of swarmpit was fine for me so far. Do you have any concerns about the login mechanism of swarmpit?
Yes, it would be possible to hide swarmpit behind the traefik service. But why would this be necessary?

In the meantime I have published the ideas of the tutorial in a conceptual project on github: https://github.com/imixs/imixs-cloud
There I have added a separate page about security: https://github.com/imixs/imixs-cloud/blob/master/doc/SECURITY.md
But also this page was more about traefik web front-end and securing a private registry. 

In swarmpit itself I haven't seen a security issue.

**Comment by matthiasbaldi** [comment]
No I don't have seen a specific issue or problem. I just asked because of the possible risk without a two factor auth and the direct access over the net (brute forcing etc).
When I have time I will push you a pull request with improvements in my Setup.

**Comment by nohaapav** [comment]
As Ralph mentioned you should have swarmpit behind the proxy. That way you can protect app from bruteforce. Swarmpit is authenticated against BE server once some data are fetched (jwt). 

> not logged-in user can see the UI

Basically layout itself is fetching some data from BE so all pages using layout are secured based on statement above only by using layout. Also every api call is secured. You should be able to see only single pages(404/403 errors) if not-logged because these are not fetching any data from BE and of course login page ..

**Comment by matthiasbaldi** [comment]
Yes that "issue" because of the UI (40x errors) I have seen in the development console of the browser.
But I think it is easy to fix over the UI routing managment.

The swarmpit proxy rules:
Yes I agree with you and @rsoika.
But what is the correct way to do that? Because the proxy is in an other Docker network as the Swarmpit is and I think this is the correct way. But do we start now an other traefik proxy instance just for Swarmpit? Or do we have there better options? Maybe I may have just not enough experience with traefik and Docker networks. :)
Thank you guys.

**Comment by nohaapav** [comment]
Well we're having proxy and swarmpit in same network. You need to have swarmpit in same network as docker-flow/traefik in case you want to expose swarmpit over proxy.

**Comment by robertofabrizi** [comment]
How can I set swarmpit to use a custom URL so that I can use that in traefik to route? Cheers!

**Comment by matthiasbaldi** [comment]
Something like this, I think:

```
version: '3'

services:
 app:
   image: swarmpit/swarmpit:latest
   environment:
     SWARMPIT_DB: http://db:5984
     JAVA_OPTS: "-Xmx512M -Xms256m"
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
   deploy:
     labels:
       - "traefik.frontend.rule=Host:swarmpit.example.com"
       - "traefik.domain = swarmpit.example.com"
       - "traefik.port=8080"
       - "traefik.enable=true"
       - "traefik.docker.network=webgateway"
....
```
