### ISSUE TITLE
swarmpit_event-collector using api 1.36 which is too new if 17.12.0 used

### ISSUE THREAD

**Issue by rossbachp** [swarmpit/swarmpit#199]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

Start a local docker dind 17.12 cluster at current docker-for-mac (17.12.0-ce-mac45 (21669))

see my github project https://github.com/bee42/traefik-with-docker

**Steps to reproduce the issue:**

```
git clone https://github.com/bee42/traefik-with-docker
cd traefik-with-docker/examples/docker-swarming-dind
./start-dind.sh
./start.swarmpit.sh
docker service logs swarmpit_event-collector
```

**What happens:**
After start current swarmpit with stack deploy the event-collector service send this message and terminate

```
swarmpit_event-collector.0.v3ft515vmz67@worker-2    | 2018/01/11 08:40:41 ERROR: Event channel error: Error response from daemon: client version 1.36 is too new. Maximum supported API version is 1.35
```

**What should happen:**

Eventcollector correct startet.

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by nohaapav** [comment]
@rossbachp Hi .. Event-collector is using by default [docker client](https://github.com/moby/moby/blob/master/client/client.go) so you can try to set env variable:

DOCKER_API_VERSION=1.35 

to make it work. 
Meanwhile i need to check why 1.36 client is used.

**Comment by rossbachp** [comment]
Works!

I change the docker-compose service definition.

```
 event-collector:
    image: swarmpit/event-collector:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    environment:
      - DOCKER_API_VERSION=1.35
...
```

Many thanks,
Peter
