### ISSUE TITLE
Feature Request - Managed Volumes

### ISSUE THREAD

**Issue by rsoika** [swarmpit/swarmpit#233]
Hi, I want to share my thoughts about a new idea/feature request concerning docker volumes. As you maybe know I am writing this open concept about a [lightweight docker swarm environment](https://github.com/imixs/imixs-cloud) where swarmpit.io is the central building block. Thanks for your great work at this point!

**The Problem:**
One problem that is often discussed in the Docker community is the lack of support for stateful containers. Lets take for example the following wordpress stack:

```
...
services:

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    deploy:
      placement:
        constraints:
         - node.role == worker
  app:
    image: wordpress:4.9.4
    volumes: 
      - wp-content:/var/www/html/wp-content
    deploy:
      placement:
        constraints:
         - node.role == worker
....
volumes:
  dbdata:
  wp-content:
....
```

You have to bind the services in some way to one specific node to avoid loosing stored data in the volumes, in case that docker swarm is moving the tasks unexpectedly. Of course you can solve this with backup service like [this one](https://github.com/imixs/imixs-docker/tree/master/backup) I have written by my own. But that's not very satisfactory. 

**Now my Idea/Question/Feature Request:**

What if I could mark my tasks in swarmpit.io as 'managed-volumes==true'. If I do this, swarmpit could mark the volume after the container was started by creating a kind of lock file (if this is possible) and stores the node name on which the task was stared.

Now in case that the container is restarted, swarmpit.io can see if the new location is different from the last one. In case the container has moved and the task is marked with 'managed-volumes==true', swarmpit.io can try to move also the volumes. 
This should be possible by moving the volume for example with SCP form the old machine to the new one. So all the data is available again on the new location.

What do you think about this?

===
Ralph
