### ISSUE TITLE
Missing user and working_dir attributes

### ISSUE THREAD

**Issue by sinacek** [swarmpit/swarmpit#278]
**Description**

I need define `user` and `working_dir` for [Node container](https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image). When I create new Stack with these container attributes, it works. But when I click on edit stack, these values is missing. 

**Steps to reproduce the issue:**
1. Create stack by 
```
version: '3'
services:
  myservice:
    image: node:8
    user: node
    working_dir: /home/node/app
    command: npm start
```

2. Edit stack by generated file
3. See the difference between origin and new file

**What happens:**
Attributes user and working_dir are missing.

**What should happen:**
Attributes user and working_dir should be generated into stack file.

**Additional information (e.g. docker version, cluster setup,...):**
Swarmpit: 1.5
Docker version 18.06.1-ce, build e68fc7a
