### ISSUE TITLE
Editing existing stackfile may modify it's service's command

### ISSUE THREAD

**Issue by Masa331** [swarmpit/swarmpit#281]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
**Description**

Hi everybody,

whenever i edit existing stackfile including service with longer command with multiple arguments the command breaks over multiple lines and container is then started with wrong(missing some args) command. This happens when editing anything in the stackfile. It's also hard to spot in the stackfile and also later when running because the service seems to redeploy ok however it may miss some important args.

**Steps to reproduce the issue:**
1. create following stackfile and save it:
```
version: '3.3'
services:
  blockchain:
    image: topmonkscom/xx-blockchain:latest
    command: ganache-cli --db /ganache_db -d --noVMErrorsOnRPCResponse -m "arrow physical twin solar host apple twin vacant grant expose truck pause silly exclude pool" -b 15 -n false -u 0,1,2
    networks:
     - net
    logging:
      driver: json-file
    environment:
      foo: bar
```
2. open stackfile for edit
the stackfile now looks like this:
```
  blockchain:
    image: topmonkscom/xixoio-blockchain:latest
    command: ganache-cli --db /ganache_db -d --noVMErrorsOnRPCResponse -m arrow physical
      twin solar host apple twin vacant grant expose truck pause silly exclude pool
      -b 15 -n false -u 0,1,2
    environment:
      foo: bar
```
command is wrapped to multiple lines and quotations are missing around params to `-m ` argument.

3. modify whatever else than command and save

**What happens:**
The service redeploys and starts with shorter command `ganache-cli --db /ganache_db -d --noVMErrorsOnRPCResponse -m arrow`

**What should happen:**
It should redeploy with full original command `ganache-cli --db /ganache_db -d --noVMErrorsOnRPCResponse -m "arrow physical twin solar host tribe twin vacant grant expose truck pause silly exclude pool" -b 15 -n false -u 0,1,2`

**Additional information (e.g. docker version, cluster setup,...):**
Swarmpit 1.6-2a0a14b in Topmonks - can show exact stackfile..
