### ISSUE TITLE
Password not getting saved? 

### ISSUE THREAD

**Issue by DeanKamali** [swarmpit/swarmpit#284]
Hey swarmpit team 

I'm using swarmpit version 1.6-2a0a14b, and  I have noticed that for when swarmpit UI container restarts I have I have to login via default login password. 

I end up changing default login password is this a known issue?

**Comment by nohaapav** [comment]
HEY,

It looks like you're using local storage for swarmpit_db(set by default) and db container has been rescheduled to another node so you lost your data. We suggest to use shared storage or at least setup constraint/placement so db is running always on pretty same dedicated node . See INSTALLATION section.

**Comment by DeanKamali** [comment]
Hey @nohaapav  
I have both items in my stack file (constraint to manager) & volume for couchdb, 
or I'm missing something? 

```
version: '3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: klaemo/couchdb:2.0.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay

volumes:
  db-data:
    driver: local
```
