### ISSUE TITLE
Can't initialize admin with manual installation

### ISSUE THREAD

**Issue by GustavoTango** [swarmpit/swarmpit#311]
**Description**
We are trying to deploy the 1.6 dashboard in our Swarm Cluster. We are using a slightly
modified version of the Stack provided in the manual installation because we are including
other services (i.e. Traefik) in this initial stack.

```yaml
version: "3.3"
services:

  # Other services omitted

  swarmpit:
    image: swarmpit/swarmpit:1.6
    environment:
      - SWARMPIT_DB=http://swarmpit_db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  swarmpit_db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M

  swarmpit_agent:
    image: swarmpit/agent:2.0
    environment:
      - EVENT_ENDPOINT=http://swarmpit:8080/events
      - HEALTH_CHECK_ENDPOINT=http://swarmpit:8080/version
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay

volumes:
  db-data:
    driver: local
```

The stack deploys without any problem and we can see the page for creating the first admin. The problem is that when we introduce the credentials to create the first admin the request fails with 
 HTTP code 401, body  `{"error":"Token invalid"}`.

![captura de pantalla 2019-02-13 a las 17 03 29](https://user-images.githubusercontent.com/38216500/52725470-92325600-2fb1-11e9-8bf3-1f183b4b4268.png)

To temporally solve this what we did was to enter in the `swarmpit_db` container and making the request to initialize the admin 
```sh
$ curl -X POST -H 'Content-Type: application/json' swarmpit:8080/initialize -d  '{"username": "admin", "password": "admin"}'
{"id":"18cf37134956801e24b3d88909001b72"}
``` 
After this, swarmpits works completely fine.

**Steps to reproduce the issue:**
1. Deploy the Stack in docker Swarm
2. Try to initialize admin from the dashboard

**What happens:**
The initialization request fails with 401 Unauthorized. Body: `{"error":"Token invalid"}`

**What should happen:**
The admin should be initialized and give access to the dashboard
