### ISSUE TITLE
Support Docker API connections over encrypted TCP

### ISSUE THREAD

**Issue by kinghuang** [swarmpit/swarmpit#318]
**Description**

Swarmpit currently requires that the Docker API be mounted as a file socket at `/var/run/docker.sock`. In my clusters, the manager nodes are configured to never take on tasks. I need a way to run Swarmpit on a non-manager node, and connect to the Docker API via a secured TCP socket (e.g., at `https://manager-here:2376` with TLS cert.

**Steps to reproduce the issue:**

1. Run Swarmpit.
2. Find no way to specify a TCP socket for the Docker API.

**What happens:**

There is no way to connect Swarmpit to a remote Docker API.

**What should happen:**

There should be a way to connect Swarmpit to a remote Docker API.

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by lumir-mrkva** [comment]
this should be supported already, try to set DOCKER_SOCK env property

**Comment by rarous** [comment]
You can deploy Socat on manager node a map Swarmpit to use it.

```
socat:
    image: rancher/socat-docker:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - net
    logging:
      driver: awslogs
    deploy:
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.1'
          memory: 8M
        limits:
          cpus: '0.1'
          memory: 8M
```

And reconfigure Swarmpit with following ENV:

```
swarmpit:
  environment:
    SWARMPIT_DOCKER_SOCK: tcp://socat:2375
```
