### ISSUE TITLE
Container can't read secret which created by swarmpit

### ISSUE THREAD

**Issue by Elecweb** [swarmpit/swarmpit#348]
**Steps to reproduce the issue:**
1. create secret by swarmpit
2. try to see content of secret file in container `/run/secrets/<name-secret>
3. content looks like it's encrypted or broken

**What happens:**
We use swarmpit for create secret but container which is attached secret can't read content of secret (it's looks like encrypted/broken) but when we create secret using docker cli `docker secret create`, container can read content of secret correctly

we test to read secret  by using `cat` secret file in container 

Is swarmpit have any encryption when create secret or it's a bug?

**What should happen:**
it should be able to read content of secret file in container 

**Additional information (e.g. docker version, cluster setup,...):**

- Docker version 18.09.4

We use docker swarm which has 2 server (1 manager and 1 worker) we deploy swarmpit image in manager and mongo (which read secret) in worker

we use [swarmpit docker compose file](https://github.com/swarmpit/swarmpit/blob/master/docker-compose.yml) for deploying swarmpit

here's docker compose file for container that use secret
```
version: "3.7"
services:
  mongo:
    image: mongo:4.0
    volumes:
      - mg:/data/db
    ports:
      - 27017:27017
    networks:
      - database-network
    secrets:
      - user-db
      - user-pass
    environment:
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/user-db
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/user-pass

volumes:
  mg:
    driver: local

secrets:
 user-db:
   external: true
 user-pass:
   external: true
```
