### ISSUE TITLE
using build context in docker-compose file fails with no error

### ISSUE THREAD

**Issue by isbkch** [swarmpit/swarmpit#349]
**Description**

Using `build context` in the docker-compose file returns error "stack deployment failed" without giving details

**Steps to reproduce the issue:**
1. http:/xxx:888/stacks/create
2. paste following 

```
version: '3.4'
services:
  app:
    build:
        context: /var/www/app/docker
        dockerfile: dockerfile
    ports:
     - 91:80
    volumes:
     - /var/www/app:/var/www/localhost/htdocs
    networks:
     - dev
  dev-mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: dev_user
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev_user
    ports:
     - 3306:3306
    volumes:
     - /var/www/docker_data/dev-mysql:/var/lib/mysql
    networks:
     - dev
  dev-proxy:
    image: haproxy:alpine
    ports:
     - 80:80
    volumes:
     - /var/www/docker_data/proxy_log:/dev/log
    networks:
     - dev
    configs:
     -
      source: Haproxy.cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
  dev-redis:
    image: redis:alpine
    ports:
     - 6381:6379
    volumes:
     - /var/www/docker_data/dev-redis-l1/:/data/
    networks:
     - dev
networks:
  dev:
    driver: overlay
configs:
  Haproxy.cfg:
    external: true

```
If I remove build context and replace it with `image` it works fine.

Here is the content of my dockerfile

```
FROM httpd:latest
COPY apache.conf /etc/apache2/conf.d/default.conf
```
