### ISSUE TITLE
Generate docker compose file : use the long syntax (>= v3.2)

### ISSUE THREAD

**Issue by sguilly** [swarmpit/swarmpit#352]
Docker compose v3.2 introduce long syntax.

Should be great if /src/clj/swarmpit/docker/engine/mapper/compose.clj could implemented the long syntax.

**ports**

```
ports:
 - "8080:80"
```

```
ports:
  - target: 80
    published: 8080
    protocol: tcp
    mode: host
```

**configs**

```
configs:
  - my_config
```

```
configs:
   - source: my_config
     target: /redis_config
     uid: '103'
     gid: '103'
     mode: 0440
```

**secrets**

```
secrets:
  - my_secret
```

```
secrets:
   - source: my_secret
     target: mypath
     uid: '103'
     gid: '103'
     mode: 0440
```
**volumes**

```
volumes:
  - mydata:/data
```

```
volumes:
   - type: volume
     source: mydata
     target: /data
     volume:
       nocopy: true
```
