### ISSUE TITLE
Overriding the user in a stack file in the Swarm ui is not reflected when getting stack info from cluster

### ISSUE THREAD

**Issue by fxdgear** [swarmpit/swarmpit#353]
When you create a stack that overrides the `user` parameter: 

```
services:
  myservice:
    image: foo/bar
    user: root   <---
```

When using the UI to inspect the service and generate the yaml file the over-ridden user is not in the list and a redeploy could result in failures cause the user param has changed.
