### ISSUE TITLE
Allow to initialise username/password via docker secrets

### ISSUE THREAD

**Issue by amitm02** [swarmpit/swarmpit#360]
Allow to initlizate the Swarmpit dashboard username/password via docker secrets.
E.g:

```
version: '3.3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
     secrets:
      - swarmpit_username_secret
      - swarmpit_password_secret

secrets:
  swarmpit_username:
    file: ./swarmpit_username.txt
  swarmpit_password_secret:
    file: ./swarmpit_password.txt
```
