### ISSUE TITLE
"No logs for given period." when there is log with "docker logs"

### ISSUE THREAD

**Issue by RemiBou** [swarmpit/swarmpit#361]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

When I go on a service or a task logs, the message "No logs for given period" is displayed while I have logs when entering "docker service logs myservice --since 30m"
**Steps to reproduce the issue:**
- Go to a service or a task
- Click Logs
- See message

**What should happen:**

The logs should be displayed

**Additional information (e.g. docker version, cluster setup,...):**

- Docker version 18.09.2, build 624796
- Swarmpit app/agent latest (1.8-11c255b displayed on the top right of the app)
- No error on the console
- XHR calls returns []

**Comment by nohaapav** [comment]
@RemiBou We're not using docker service logs API as primary source for logs see [1.7 RELEASE NOTE](https://github.com/swarmpit/swarmpit/releases/tag/1.7)

Is everything set as expected e.g. agent label ? If yes could you copy paste logs from agents ? There should be GET log requests to containers associated with service.

**Comment by RemiBou** [comment]
Here is my swarmpit stack definition

```yml
version: '3.3'
# I use this instead of swarmpit installer because it doesn't support volume driver with slash like rexray/cinder
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data2:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db-data2:
    driver: "local"
    driver_opts:
      type: none
      device: /swarm/volumes/swarmpit 
      o: bind
```

**Comment by nohaapav** [comment]
@RemiBou See new stack agent definition. You're missing `swarmpit.agent` label. See:

<img width="981" alt="Screen Shot 2019-06-05 at 4 12 05 PM" src="https://user-images.githubusercontent.com/4179104/58963067-cfaf2f00-87ac-11e9-881b-c1f324a7ace5.png">

**Comment by RemiBou** [comment]
I added it, and I also added the following env variable on the agent because of my port config on the app

```yml

    environment:
      - DOCKER_API_VERSION=1.35
      - EVENT_ENDPOINT=http://app:888/events
      - HEALTH_CHECK_ENDPOINT=http://app:888/version
```

**Comment by nohaapav** [comment]
Is your agent even running ? 

```

**Comment by RemiBou** [comment]
The agent is running yes here are the logs after changing the env variables

> XXX    | 2019/06/05 14:28:29 INFO: Waiting for Swarmpit...
> XXX    | 2019/06/05 14:28:34 INFO: Swarmpit OK
> XXX    | 2019/06/05 14:28:34 INFO: Event collector started.
> XXX    | 2019/06/05 14:28:34 INFO: Stats collector started.

**Comment by mrloud** [comment]
I'm in the same situation, no logs are showing for me either.

**Comment by mrloud** [comment]
Nevermind, I'm getting logs now.

**Comment by nohaapav** [comment]
@RemiBou Did you get your logs working ? If not please paste complete compose that you're using ..

**Comment by RemiBou** [comment]
No it's not working yet, here is my compose

```yml
version: '3.3'
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data2:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    labels:
      swarmpit.agent: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db-data2:
    driver: "local"
    driver_opts:
      type: none
      device: /swarm/volumes/swarmpit 
      o: bind
```
