### ISSUE TITLE
Support container labels

### ISSUE THREAD

**Issue by dstepanov** [swarmpit/swarmpit#364]
Right now swarmpit only supports deploy labels.

Container labels are defined on the service level:
```
services:
  web_api:
    labels:
      filebeat: 'true'
```
Deploy labels are defined on the services' deploy level:
```
services:
  web_api:
    deploy:
      labels:
        filebeat: 'true'
```
Deploy labels are not added to the "Edit stack" definition.         

Container label is mixed with other 'com.docker' labels when inspected, to create it should be enough to ignore 'com.docker' prefix.

My use case is to use ELK's filebeat configured to pick up specific containers based on the label, which works but the label is missing next time I want to edit the stack.

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html
