### ISSUE TITLE
Context path and reverse proxy (as traefik)

### ISSUE THREAD

**Issue by lucaspouzac** [swarmpit/swarmpit#413]
Hi, is it possible to configure swampit behind a reverse proxy with a context path (#326) ?

Maybe, you need use x-forwarded-prefix header to add path-prefix ? https://docs.traefik.io/v1.7/basics/#matchers

```
app:
    image: swarmpit/swarmpit:1.8
      deploy:
        labels:
          traefik.port: 8080
          traefik.frontend.rule: "Host:${DOMAIN};PathPrefixStrip:/swarmpit/"
```

Actually, I get 404 because index.html assumes that css and js folders are located in the root folder.

![image](https://user-images.githubusercontent.com/758899/69147726-0070ef80-0ad3-11ea-92d9-612e87836c43.png)
