### ISSUE TITLE
Deploy error when service have healthcheck 

### ISSUE THREAD

**Issue by reg2005** [swarmpit/swarmpit#469]
**When I change the service configuration using Swarmpit I get the error  "Service update failed.". This bug appears only with the services which have healthcheck**

If the service doesn’t have healtcheck option - the Deploy works correctly

**Steps to reproduce the issue:**
1. Add healtcheck option in docker-stack config

```yaml
version: '3.7'
services:
    app:
      image: $REPOSITORY_URL:${CI_COMMIT_SHA}
      deploy:
        replicas: 3
        update_config:
          parallelism: 1
          order: start-first
          failure_action: rollback
        rollback_config:
          parallelism: 1
          order: start-first
        resources:
          limits:
            cpus: "1"
            memory: 1430M
        restart_policy:
          delay: 5s
          window: 20s
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3333/healthcheck"]
        interval: 5s
        timeout: 3s
        retries: 7
      command: node server.js
```

2. Deploy this stack using CLI
3. Try to edit service config using Swarmpit and click "Deploy"

**What happens:**
I get the error "Service update failed."

![image](https://user-images.githubusercontent.com/4133683/74090832-31a10080-4ac1-11ea-8547-3dcaa37fc11f.png)

`POST status 400: https://swarmpit.force.taxi/api/services/gz62s5wiiz6e7ph4vf9iyvebp
`
![image](https://user-images.githubusercontent.com/4133683/74090839-3fef1c80-4ac1-11ea-81af-b7113983204a.png)

**What should happen:**
Success deploy

**Additional information (e.g. docker version, cluster setup,...):**
Latest Swarmit version v1.9-1687920
