### ISSUE TITLE
Feature request: implement docker compose v3.3 deploy placement preferences

### ISSUE THREAD

**Issue by bboh** [swarmpit/swarmpit#488]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Please support deploy.placement.preferences in[ compose schema v3.3 ](https://github.com/docker/compose/blob/f1083087dfe7ea2fe729d8be8ee037e166481930/compose/config/config_schema_v3.3.json)

This is necessary to spread replicas across availability zones for high available applications.
minimal example compose file:
```
version: '3.3'
services:
  whoami-test-app:
    image: containous/whoami:v1.3.0
    logging:
      driver: json-file
    deploy:
      replicas: 3
      placement:
        constraints:
         - node.role == worker
        preferences:
         - spread: node.labels.az

```

**Description**
The stack with this property cannot be deployed.

**Steps to reproduce the issue:**
1. paste the aforementioned stack and try to deploy in swarmpit 

**What happens:**
swarmpit shows the error message
> Stack update failed. preferences Additional property preferences is not allowed

**What should happen:**
Deployment succeeds

**Additional information (e.g. docker version, cluster setup,...):**
swarmpit 1.8
ops@manager01:~$ sudo docker -v
Docker version 19.03.6, build 369ce74a3c
swarm with 3 manager and 3 worker nodes in different availability zones
