### ISSUE TITLE
Host published ports are lost

### ISSUE THREAD

**Issue by cpoetter** [swarmpit/swarmpit#493]
**Description**
If you create a stack which exposes ports in the `host` mode instead of the default `ingress` mode, the first deployment works. But when you then click the `Edit` button and look at the *re-created* stack file, the information that the ports were published in the `host` mode is lost.

**Steps to reproduce the issue:**
1. Create a new stack called `nginx` with the following stack file and deploy it.
```
version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        mode: host
```
2. Visit the detail page of the service `nginx_nginx`. Port 80 was successfully published in `host` mode.
3. Go back to the **Stacks** section and edit the `nginx` stack. You will notice that the `host` information is gone:
```
version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
     - 80:80
    networks:
     - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay
```
4. Don't change anything and just click `Deploy`
5. Visit again the `nginx_nginx` detail page. 

**What happens:**
Port 80 is not published in `ingress` mode. 

**What should happen:**
Port 80 should still be published in `host` mode. Also the stack file should contained the information that the ports were published in `host` mode in step 3.

**Additional information (e.g. docker version, cluster setup,...):**
- Ubuntu 18.04.4 LTS
- Docker version 19.03.6, build 369ce74a3c
- Swarmpit v1.9-0b9f47a

Additionally to the above mentioned steps you can also create a *Service* through the Swarmpit interface and when publish ports select the host mode. Once deployed click on arrow next to the `Edit` button and select `Compose`. You will see the `host` information is lost.
