### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by AlexGustafsson** [swarmpit/swarmpit#506]
**Description**

I'm trying to start swarmpit on a Fedora CoreOS stack. The `swarmpit_app` keeps failing to start.

I've tried to debug the issue as well as reading through previous issues, but I fail to find anything resembling this issue. 

**Steps to reproduce the issue:**
1. Run the included docker stack compose file

**What happens:**

I get one of these two logs each time the service starts:

```
swarmpit_app.1.pqs09p4zn75j@nl-ams-alfa    | INFO: Swarmpit is starting...
swarmpit_app.1.pqs09p4zn75j@nl-ams-alfa    | May 19, 2020 9:40:46 PM swarmpit.database invoke
swarmpit_app.1.pqs09p4zn75j@nl-ams-alfa    | INFO: Waiting for CouchDB ...
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | May 19, 2020 9:37:20 PM swarmpit.server invoke
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | INFO: Swarmpit is starting...
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | May 19, 2020 9:37:20 PM swarmpit.database invoke
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | INFO: Waiting for CouchDB ...
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | May 19, 2020 9:39:04 PM swarmpit.database invoke
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | SEVERE: ... timeout
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | Exception in thread "main" java.lang.IllegalArgumentException: Additional data must be non-nil.
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:31)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:22)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.core$ex_info.invokeStatic(core.clj:4783)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.core$ex_info.invoke(core.clj:4783)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.database$wait_for_db.invokeStatic(database.clj:31)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.database$wait_for_db.invoke(database.clj:22)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.database$init_couch.invokeStatic(database.clj:58)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.database$init_couch.invoke(database.clj:56)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.database$init.invokeStatic(database.clj:75)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.database$init.invoke(database.clj:73)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.server$_main.invokeStatic(server.clj:92)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.server$_main.doInvoke(server.clj:90)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
swarmpit_app.1.su6rw2250ljb@nl-ams-alfa    | 	at swarmpit.server.main(Unknown Source)
```

```
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # A fatal error has been detected by the Java Runtime Environment:
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #  SIGSEGV (0xb) at pc=0x00007f22f7780529, pid=1, tid=0x00007f22f8550700
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # Problematic frame:
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # C  [libc.so.6+0x34529]  abort+0x269
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # Core dump written. Default location: /usr/src/app/core or core.1
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # An error report file with more information is saved as:
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # /usr/src/app/hs_err_pid1.log
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # If you would like to submit a bug report, please visit:
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #   http://bugreport.java.com/bugreport/crash.jsp
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # The crash happened outside the Java Virtual Machine in native code.
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | # See problematic frame for where to report the bug.
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | #
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | [error occurred during error reporting , id 0xb]
[... repeated dozens of times ...]
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | [error occurred during error reporting , id 0xb]
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | [Too many errors, abort]
[... repeated dozens of times ...]
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | [Too many errors, abort]
swarmpit_app.1.goo84o737yal@se-kna-foxtrot    | library initialization failed - unable to allocate file descriptor table - out of memory
```

**What should happen:**

The application should start.

**Additional information (e.g. docker version, cluster setup,...):**

Output of `docker stack ps swarmpit`:

```
tt86h820tymg        swarmpit_agent.sn7f5zs9544cao1dsap272uq8   swarmpit/agent:latest   host-1      Running             Running 11 minutes ago                                 
jn27lmkxzccv        swarmpit_agent.n687g8nvlkyt61mra47o8gjhz   swarmpit/agent:latest   host-2      Running             Running 11 minutes ago                                 
t2p4m9onzqo3        swarmpit_agent.m4n1fzfvbig8d4eu32r8tldrs   swarmpit/agent:latest   host-3      Running             Running 11 minutes ago                                 
lsxuqaioz4ov        swarmpit_agent.juqnb01axzwfe4ysjhn4k38dp   swarmpit/agent:latest   host-4      Running             Running 11 minutes ago                                 
g4e2i98cnrz0        swarmpit_agent.bktzuk69phtacpav0fjahocdy   swarmpit/agent:latest   host-5      Running             Running 11 minutes ago                                 
nrcxro6e317w        swarmpit_agent.84yv6zw0olgqmw51omuevrirn   swarmpit/agent:latest   host-6      Running             Running 11 minutes ago                                 
l73hwdnvm6kf        swarmpit_app.1                             swarmpit/swarmpit:1.9   host-1      Running             Running 9 seconds ago                                  
oct0tjp3vrlg         \_ swarmpit_app.1                         swarmpit/swarmpit:1.9   host-3      Shutdown            Failed 15 seconds ago    "task: non-zero exit (139)"   
y27wvf6iq6rp         \_ swarmpit_app.1                         swarmpit/swarmpit:1.9   host-1      Shutdown            Failed 22 seconds ago    "task: non-zero exit (1)"     
v6cww78pq88i         \_ swarmpit_app.1                         swarmpit/swarmpit:1.9   host-3      Shutdown            Failed 3 minutes ago     "task: non-zero exit (139)"   
nt7qol3d3t4i         \_ swarmpit_app.1                         swarmpit/swarmpit:1.9   host-3      Shutdown            Failed 3 minutes ago     "task: non-zero exit (139)"   
sk82mkf5rmbf        swarmpit_influxdb.1                        influxdb:1.7            host-5      Running             Running 11 minutes ago                                 
7r9942pmxn27        swarmpit_db.1                              couchdb:2.3.0           host-6      Running             Running 11 minutes ago                             
```

Docker stack compose file:

```yaml
version: '3.7'

services:
  agent:
    image: swarmpit/agent:latest
    environment:
      DOCKER_API_VERSION: '1.39'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - traefik-swarmpit
    logging:
      driver: journald
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.05'
          memory: 32M
        limits:
          cpus: '0.1'
          memory: 64M
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      SWARMPIT_DB: http://db:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - traefik-swarmpit
    logging:
      driver: journald
    deploy:
      labels:
        traefik.http.services.swarmpit.loadbalancer.server.port: '8080'
        traefik.http.routers.swarmpit.rule: Host(`swarmpit.example.com`)
        traefik.http.routers.swarmpit.service: swarmpit
        traefik.enable: 'true'
        traefik.http.routers.swarmpit.tls: 'true'
        traefik.http.routers.swarmpit.entrypoints: https
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
  db:
    image: couchdb:2.3.0
    volumes:
     - /var/mnt/gluster/gv0/swarmpit/couchdb:/opt/couchdb/data
    networks:
     - traefik-swarmpit
    logging:
      driver: journald
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.15'
          memory: 128M
      placement:
        constraints:
          - node.labels.gluster == true
  influxdb:
    image: influxdb:1.7
    volumes:
     - /var/mnt/gluster/gv0/swarmpit/influxdb:/var/lib/influxdb
    networks:
     - traefik-swarmpit
    logging:
      driver: journald
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
      placement:
        constraints:
          - node.labels.gluster == true

networks:
  traefik-swarmpit:
    external: true
```
