### ISSUE TITLE
Main dashboard is not showing services graph: Memory and CPU

### ISSUE THREAD

**Issue by Gabrirf** [swarmpit/swarmpit#520]
**Description**

After a while using Swarmpit, I deleted all volumes to do a clean deploy. Once I did it, the main dashboard doesn't show ram and cpu services resources graph anymore.

![Here the div space where RAM Ploty should be](https://user-images.githubusercontent.com/36746948/84151052-0f18f700-aa63-11ea-9109-39306033d173.png)

There is a request failing: /api/services/ts/cpu and /api/services/ts/memory

![Console log error](https://user-images.githubusercontent.com/36746948/84151364-8d759900-aa63-11ea-8daa-235f37aa8d2c.png)

It's look like an InfluxDB bad use.

![Response details of error request](https://user-images.githubusercontent.com/36746948/84151558-d9284280-aa63-11ea-9c3e-4ef876583952.png)

**Steps to reproduce the issue:**
1. In a clean environment, with all container, images, networks and volumes removed, enter in a cluster with `docker swarm init --advertise-addr 127.0.0.1`
2. Launch swarmpit with a docker-compose file: 

```yaml
version: '3.3'
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.role == manager
  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
networks:
  net:
    driver: overlay
    attachable: true
volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
```

3. Go to 127.0.0.1:8080 in browser. (First time will ask for a password, and then you can log in)

**What happens:**

Doesn't show services ploty graph. Something is failing with influxDB

**What should happen:**

It should show services ploty graph

**Additional information (e.g. docker version, cluster setup,...):**

Defined at deploy steps
