### ISSUE TITLE
Huge memory difference on the same Swarmpit version

### ISSUE THREAD

**Issue by ramonck** [swarmpit/swarmpit#551]
Without the agents and influxdb and still on the old couchdb.
The light version
```
version: '3'
services:
 app:
   image: swarmpit/swarmpit:1.9
   environment:
     SWARMPIT_DB: http://db:5984
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
   ports:
     - 888:8080
   networks:
     - net
   deploy:
     placement:
       constraints:
         - node.role == manager
 db:
   image: klaemo/couchdb:2.0.0
   volumes:
     - db-data:/opt/couchdb/data
   networks:
     - net
networks:
   net:
     driver: overlay
volumes:
   db-data:
     driver: local
```

The memory heavy duty version
```
version: '3.3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M

  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 128M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
```

Compare those two setups and let me know the memory difference, it's insane.
Not sure if it's couchDB docker image that is doing this or the agents, something is pushing this to the top.

You should launch two docker compose files, the light version without the influxdb, agents and the new couchdb and the other "full" version which has the agents and everything else.

It's crazy this difference in memory consumption should really be looked at, the light version doesn't even make a difference in terms of memory the full version is a memory insane process not sure why, maybe look into the agents or the influxdb process, not sure.. very weird.
