### ISSUE TITLE
worker node resource monitoring, not showing

### ISSUE THREAD

**Issue by rshahrami** [swarmpit/swarmpit#560]
**Description**

I executed the swarmpit with the following commands. When the swarmpit is executed, the Master node resources are displayed, but the Worker node resources remain loading. Of course, the containers run in it is displayed.

`git clone https://github.com/swarmpit/swarmpit -b master  or  git clone https://github.com/swarmpit/swarmpit -b 1.19`
`docker stack deploy -c swarmpit/docker-compose.yml swarmpit`

add flowing text to deploy db service in compose file:

`      placement:
        constraints:
          - node.role == manager`

**What happens:**
the Worker node resources monitor, remain loading but the containers run in it is displayed

![Capture](https://user-images.githubusercontent.com/57341758/94337141-0ab62100-fff5-11ea-9638-723230953518.PNG)

**Additional information (e.g. docker version, cluster setup,...):**

docker Version:          19.03.9
API version:                1.40
master cpu:                10 core
master memory:         4300 MiB
worker cpu:                10 coer
worker memory          3200 MiB

**Comment by nohaapav** [comment]
Is `swarmpit_agent` running on that node ? Can you share your stackfile please ?

**Comment by rshahrami** [comment]
hi I apologize for the late reply. swarmpit_agent is running in master and worker node. stackfile is sent to the attachment. 

    On Saturday, September 26, 2020, 02:21:09 PM GMT+3:30, Pavol Noha <notifications@github.com> wrote:  
 
 


Is swarmpit_agent running on that node ? Can you share your stackfile please ?

**Comment by rshahrami** [comment]
> Is `swarmpit_agent` running on that node ? Can you share your stackfile please ?

**Comment by rshahrami** [comment]
hi I apologize for the late reply. swarmpit_agent is running in master and worker node. stackfile is sent to the attachment. 

`version: '3.3'

services:
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
      placement:
        constraints:
          - node.role == manager

  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 128M

  agent:
    image: swarmpit/agent:2.2
    environment:
      - DOCKER_API_VERSION=1.35
      - HEALTH_CHECK_ENDPOINT=http://app:8080/version
      - EVENT_ENDPOINT=http://app:8080/events
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
`

**Comment by nohaapav** [comment]
Looks solid. Can you share agent logs from the worker node ?

**Comment by rshahrami** [comment]
swarmpit logs in worker node : 

`docker logs 9b6d37779ce7
2020/09/26 08:33:29 INFO: Waiting for Swarmpit...`

**Comment by nohaapav** [comment]
Looks like agent can't connect to Swarmpit. Probably some network issue with your cluster setup.

**Comment by rshahrami** [comment]
What do you think is the problem? Is there a problem with the ports?

**Comment by nohaapav** [comment]
@rshahrami Not sure. Most probably some issue with overlay network.

**Comment by rshahrami** [comment]
What do you think is the problem? Is there a problem with the ports?

**Comment by sudo8com** [comment]
I was able to replicate this problem running behind Traefik 2

ubuntu@ip-172-31-1-45:~/swarmpit$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
h2gu3yuklovz5y7rqifg1oer8 *   ip-172-31-1-45      Ready               Active              Leader              19.03.8
trwi8hpalv1sex4hyfbn8c9wd     ip-172-31-8-20      Ready               Active              Reachable           19.03.8
idxltlm90o7caugv7ay2hzt1d     ip-172-31-8-78      Ready               Active              Reachable           19.03.8
iv61q4al3vl6ndxw46ogx4vu7     ip-172-31-9-71      Ready               Active                                  19.03.8
ubuntu@ip-172-31-1-45:~/swarmpit$ docker service logs swarmpit_agent
swarmpit_agent.0.xguonaexlku5@ip-172-31-1-45    | 2020/10/30 00:49:41 INFO: Waiting for Swarmpit...
swarmpit_agent.0.xguonaexlku5@ip-172-31-1-45    | 2020/10/30 00:50:16 INFO: Swarmpit OK
swarmpit_agent.0.xguonaexlku5@ip-172-31-1-45    | 2020/10/30 00:50:16 INFO: Event collector started.
swarmpit_agent.0.xguonaexlku5@ip-172-31-1-45    | 2020/10/30 00:50:16 INFO: Stats collector started.
swarmpit_agent.0.dgk3n37fkanf@ip-172-31-8-20    | 2020/10/30 00:49:41 INFO: Waiting for Swarmpit...
swarmpit_agent.0.ps7gpiomsoyu@ip-172-31-8-78    | 2020/10/30 00:49:42 INFO: Waiting for Swarmpit...
swarmpit_agent.0.obitflmnz00l@ip-172-31-9-71    | 2020/10/30 00:49:42 INFO: Waiting for Swarmpit...

**Comment by daominhsangvn** [comment]
I have the same issue then i disabled firewall in worker node then it's become working.
```
time="2020-11-16T08:18:46Z" level=info msg="Starting node_exporter (version=0.16.0, branch=HEAD, revision=d42bd70f4363dced6b77d8fc311ea57b63387e4f)" source="node_exporter.go:82"
time="2020-11-16T08:18:46Z" level=info msg="Build context (go=go1.9.6, user=root@a67a9bc13a69, date=20180515-15:52:42)" source="node_exporter.go:83"
time="2020-11-16T08:18:46Z" level=info msg="Enabled collectors:" source="node_exporter.go:90"
time="2020-11-16T08:18:46Z" level=info msg=" - arp" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - bcache" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - bonding" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - conntrack" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - cpu" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - diskstats" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - edac" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - entropy" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - filefd" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - filesystem" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - hwmon" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - infiniband" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - loadavg" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - mdadm" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - meminfo" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - netdev" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - netstat" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - nfs" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - nfsd" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - sockstat" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - stat" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - textfile" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - time" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - timex" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - uname" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - vmstat" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - wifi" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - xfs" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg=" - zfs" source="node_exporter.go:97"
time="2020-11-16T08:18:46Z" level=info msg="Listening on :9100" source="node_exporter.go:111"
```

**Comment by amir-abdi** [comment]
Same problem here.
I'm running a worker node in EC2 in a public subnet, and the Leader node is in another private subnet (same VPC). I have tried openning 8080 and 888 ports on both instances, no luck so far. 

I see the following in the logs of the swarm agent running on the worker node:
```
2021/04/11 22:20:02 INFO: Waiting for Swarmpit...
```

**Comment by nohaapav** [comment]
The problem is that swarmpit agent can't see swarmpit. See this [section](https://github.com/swarmpit/agent#parameters) 

```
*EVENT_ENDPOINT* - default to http://app:8080/events
*HEALTH_CHECK_ENDPOINT* - default to http://app:8080/version
```

**Comment by amir-abdi** [comment]
Thank you @nohaapav  for your quick response. 

> The problem is that swarmpit agent can't see swarmpit. See this [section](https://github.com/swarmpit/agent#parameters) 

But I haven't changed any default parameters. Why can't the agent see the swarmpit? The ports are supposed to be open on both EC2 instances. What am I missing?

> You have to probably change default EVENT_ENDPOINT & HEALTH_CHECK_ENDPOINT in order to make it work unless the services share same overlay network or there is some advanced network configuration in place.

What do you mean by services share same overlay network? In the stack config yaml file (shared above) there is an overlay network and all services are part of that. Isn't that enough?

**Comment by nohaapav** [comment]
It is in ideal world. But maybe something on network layer causing the issue with overlay network. You have to debug the problem yourself. Simply try to deploy new service within same network and try to `ping` swarmpit to see if there is no issue.

**Comment by amir-abdi** [comment]
By opening all traffic between the two servers, the problem was solved. 
BUT, I'm not happy with this decision. I don't like wildcard network permissions between servers. I want to be as constraining as possibly. 

So, does anyone know what are the minimum ports (888? 8080? 80?) and protocols (ICMP for ping? TCP? UDP?) that need to be enabled between workers and manager nodes?

And from which to which? (worker to manager or vice versa)?

**Comment by nohaapav** [comment]
@amir-abdi 

1. Agents send events and statistics back to Swarmpit so this is one way:
`swarmpit_agent -> swarmpit_app`
2. Swarmpit call Agents in order to get service logs:
`swarmpit_app -> swarmpit_agent`

So traffic is bidirectional. Internally both Swarmpit & Agent expose port 8080.

**Comment by amir-abdi** [comment]
@nohaapav Unfortunately, I don't think all communications are TCP/8080. I have openned those ports, and the stats of the worker node still did not show up. It only showed up when I openned all traffic.

**Comment by nohaapav** [comment]
@amir-abdi On Swarmpit <-> Agent side everything is TCP. Maybe docker overlay using some magic behind.

**Comment by Ewpratten** [comment]
For people that wanted firewall rules, this guide fixed all my issues with nodes not getting data from eachother.

https://www.digitalocean.com/community/tutorials/how-to-configure-the-linux-firewall-for-docker-swarm-on-ubuntu-16-04

Just had to open up the generic docker swarm ports

**Comment by jdevstart** [comment]
Been learning for the last few months about docker, docker-compose, docker-swarm, etc.

For anyone that might still be looking into this, I was running into the same issue and was able to fix the agent not reporting by changing the following:

From:
 ```
ports:
      - 888:8080
```
To:
```
ports:
      - target: 8080
      - published: 888
      - mode: host
```

**Comment by Leopere** [comment]
> The problem is that swarmpit agent can't see swarmpit. See this [section](https://github.com/swarmpit/agent#parameters)
> 
> ```
> EVENT_ENDPOINT - default to http://app:8080/events
> HEALTH_CHECK_ENDPOINT - default to http://app:8080/version
> ```
> 
> You have to probably change default EVENT_ENDPOINT & HEALTH_CHECK_ENDPOINT in order to make it work unless the services share same overlay network or there is some advanced network configuration in place.

This appears to have fixed my issue as well and I'm running mine behind Træfik 2.x.

**Comment by NgHuuAn** [comment]
I used swarm cluster with 1 master node and 2 client node and I got the same problem, my log show 

```
docker container logs swarmpit_agent.6h3oo3lxr6n8f8j5rm1rgowrf.oxyr6wng6vuwis6cehwrz1yqo
2022/07/21 08:52:58 INFO: Waiting for Swarmpit...
```

1. I try open firewall via tables for all node but not solved !

`iptables -A INPUT -j ACCEPT`

2. I try to change network type host but not work: 

```
version: '3.3'

services:

  traefik:
    # Use the latest Traefik image
    image: traefik:v2.2
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.traefik-public.traefik-public-certificates == true
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik-public
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        # That way you can add other internal Traefik instances per stack if needed
        - traefik.constraint-label=traefik-public
        # admin-auth middleware with HTTP Basic auth
        # Using the environment variables USERNAME and HASHED_PASSWORD
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # traefik-http set up only to use the middleware to redirect to https
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        # traefik-https the actual router using HTTPS
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        # Use the special Traefik service api@internal with the web UI/Dashboard
        - traefik.http.routers.traefik-public-https.service=api@internal
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        # Define the port inside of the Docker service to use
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the volume to store the certificates
      - traefik-public-certificates:/certificates
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      # Create an entrypoint "http" listening on address 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on address 443
      - --entrypoints.https.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

volumes:
  # Create a volume to store the certificates, there is a constraint to make sure
  # Traefik is always deployed to the same Docker node with the same volume containing
  # the HTTPS certificates
  traefik-public-certificates:

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
```

My YAML stack confg look like: 

version: '3.3'
services:
  agent:
    image: swarmpit/agent:latest
    environment:
      DOCKER_API_VERSION: '1.35'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.05'
          memory: 32M
        limits:
          cpus: '0.1'
          memory: 64M
  app:
    image: swarmpit/swarmpit:latest
    environment:
      SWARMPIT_DB: http://db:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - net
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmpit-https.entrypoints: https
        traefik.http.routers.swarmpit-https.tls.certresolver: le
        traefik.http.routers.swarmpit-http.rule: Host(`swarm-manager.svtech.local`)
        traefik.http.routers.swarmpit-http.middlewares: https-redirect
        traefik.http.services.swarmpit.loadbalancer.server.port: '8080'
        traefik.http.routers.swarmpit-http.entrypoints: http
        traefik.constraint-label: traefik-public
        traefik.http.routers.swarmpit-https.rule: Host(`swarm-manager.svtech.local`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.swarmpit-https.tls: 'true'
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.5'
          memory: 1024M
  db:
    image: couchdb:2.3.0
    volumes:
     - db-data:/opt/couchdb/data
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.labels.swarmpit.db-data == true
      resources:
        reservations:
          cpus: '0.15'
          memory: 256M
        limits:
          cpus: '0.3'
          memory: 512M
  influxdb:
    image: influxdb:1.7
    volumes:
     - influx-data:/var/lib/influxdb
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.labels.swarmpit.influx-data == true
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
networks:
  net:
    driver: overlay
  traefik-public:
    external: true
volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
