### ISSUE TITLE
Volume type `npipe` in docker-compose file not supported

### ISSUE THREAD

**Issue by carldebilly** [swarmpit/swarmpit#563]
While trying to deploy an image using `npipe` as volume type on Windows will work well.

If we create the following stack file:

# Situation
``` yaml
version: '3.3'
services:
  agent-win:
    image: portainer/agent
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
      - type: bind
        source: C:\ProgramData\docker\volumes
        target: C:\ProgramData\docker\volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == windows]
  [...]
```

# The problem
... it works, but if you reload the file in swarmpit GUI, you'll get the following:

``` yaml
version: '3.3'
services:
  agent-win:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
     - /tmp/\\.\pipe\docker_engine:\\.\pipe\docker_engine
     - C:\ProgramData\docker\volumes:C:\ProgramData\docker\volumes
    networks:
     - agent-network
    logging:
      driver: json-file
    deploy:
      mode: global
      restart_policy:
        condition: none
      placement:
        constraints:
         - node.platform.os == windows
```

You can see not only the `type: npipe` dissapear, but a strange `/tmp/` is added. If you try to save this file again, it will fail with the following error:
![image](https://user-images.githubusercontent.com/4174207/97097110-1a9c4180-1643-11eb-9812-9b6adf92e7bb.png)

# The expectation
Using `type: npipe` in the stack _docker-compose_ definition should work and persists as-is.
