### ISSUE TITLE
Specifying isolation mode not supported

### ISSUE THREAD

**Issue by carldebilly** [swarmpit/swarmpit#564]
# BUG REPORT

# Description

**Steps to reproduce the issue:**
1. Add a Windows Server 20H2 to your swarm
2. Create a new stack with a service running on a previous version of Windows. Example: `mcr.microsoft.com/windows/nanoserver:1809`
3. Set the version to `3.5`
4. Specify the isolation mode in your service to `hyperv`
5. **FAIL**: Start the service : it will fail with the following error:
    ![image](https://user-images.githubusercontent.com/4174207/97097588-40781500-1648-11eb-8ff5-04adae9131c4.png)
6. Change for another image to use a version not requiring the `isolation: hyperv` like `mcr.microsoft.com/windows/nanoserver:20H2`
7.  It works because it's using the `process` isolation mode.

## What happens:
The isolation mode is ignored and the service is deployed as Windows default mode (`process`).

## What should happen
The isolation mode specified should be used to deploy the service.

## Additional information

Faulty stack definition:

``` yaml
version: '3.5' #this is the first version supporting `isolation:` directive
services:
  win:
    image: mcr.microsoft.com/windows/nanoserver:1809
    isolation: hyperv #this command is ignored but required for a 1809 image to run on a 20H2 machine
    deploy:
      restart_policy:
        condition: none
```

Docker documentation about `isolation:` directive: https://docs.docker.com/compose/compose-file/#command
