### ISSUE TITLE
Can't login/register on new setup

### ISSUE THREAD

**Issue by waynehaffenden** [swarmpit/swarmpit#570]
**Description**

I've setup a brand new swarmpit setup with the following config, I initially receive the register UI but when clicking the button nothing happens and then traefik times out with communicating with swarmpit. Used the curl workaround to create initial user, the receive login UI but again when pressing button same thing happens as before. Checked docker logs and service appears to be running. I do receive a bunch of 401 errors in the console though!

```
version: "3.8"

services:
  app:
    image: swarmpit/swarmpit
    ports:
      - 888:8080
    networks:
      - internal
      - cosmos-ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SWARMPIT_DB: http://db:5984
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swarmpit.rule=Host(`swarm.DOMAINHERE`)"
        - "traefik.http.routers.swarmpit.entrypoints=https"
        - "traefik.http.routers.swarmpit.tls.certresolver=cloudflare"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"

  db:
    image: couchdb:2.3
    networks:
      - internal
    volumes:
      - /swarm/swarm/data:/opt/couchdb/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  agent:
    image: swarmpit/agent
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

networks:
  internal:
    driver: overlay
    attachable: true
  cosmos-ingress:
    external: true
```

**Steps to reproduce the issue:**
1. Run docker stack deploy
2. Access web interface
3. Press Register/Login button

**What happens:**

Nothing visually but service becomes unavailable.

**What should happen:**

Able to login/register.

**Additional information (e.g. docker version, cluster setup,...):**
