### ISSUE TITLE
Unable to Deploy from Private v2 Registry

### ISSUE THREAD

**Issue by ztimson** [swarmpit/swarmpit#605]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

**Steps to reproduce the issue:**
1. Create a v2 registry (See attached compose file)
2. Push an image to the registry
3. Add the registry to Swarmpit
4. Try and deploy the image from the registry

**What happens:**
The image never get's actually deployed.
The status goes into a loop of preparing -> running (but only for a brief second) -> complete.
The logs & status message is empty as if it never got past preparing.
![image](https://user-images.githubusercontent.com/5761827/119596113-995d8680-bdac-11eb-81d5-e65974f53b76.png)

**What should happen:**
Swarmpit should use my saved credentials to pull the image from my private repository & deploy it

**Additional information (e.g. docker version, cluster setup,...):**
- I am using traefik to add HTTPS however the registry appears to be working as expected (I can push & pull images via cli without issue)
- There is no issue adding the registry & logging in via Swarmpit
- When I select the registry from the service screen, swarmpit appears to list all the images without issue
- I logged into the repository manually on each node using the root user but that didn't change anything (Does that even required?)

My compose file for the registry:
```
version: '3.7'
services:
  docker:
    image: registry:latest
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: PSD Docker Registry
    volumes:
     - /storage/images:/var/lib/registry
     - /storage/passwords:/auth
    networks:
     - default
     - traefik
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.services.docker.loadbalancer.server.port: '5000'
        traefik.http.routers.docker_insecure.entrypoints: web
        traefik.http.routers.docker_insecure.middlewares: https-redirect
        traefik.http.routers.docker_insecure.rule: Host("docker.example.com")
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.http.routers.docker.entrypoints: websecure
        traefik.http.routers.docker.rule: Host("docker.example.com")
        traefik.http.routers.docker.tls.certresolver: letsencryptresolver
        traefik.enable: 'true'
  docker-ui:
    image: joxit/docker-registry-ui:latest
    environment:
      DELETE_IMAGES: 'true'
      NGINX_PROXY_PASS_URL: http://docker:5000
      REGISTRY_TITLE: PSD Docker Registry
      SINGLE_REGISTRY: 'true'
    networks:
     - default
     - traefik
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.docker-ui.tls.certresolver: letsencryptresolver
        traefik.http.routers.docker-ui_insecure.middlewares: https-redirect
        traefik.http.routers.docker-ui_insecure.entrypoints: web
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.http.routers.docker-ui.entrypoints: websecure
        traefik.http.routers.docker-ui_insecure.rule: Host("dockerhub.example.com")
        traefik.http.services.docker-ui.loadbalancer.server.port: '80'
        traefik.http.routers.docker-ui.rule: Host("dockerhub.example.com")
        traefik.enable: 'true'
networks:
  default:
    driver: overlay
  traefik:
    external: true

```
