### ISSUE TITLE
Change URL Path

### ISSUE THREAD

**Issue by lukezamboni** [swarmpit/swarmpit#610]
I am trying to make Swarmpit work with Traefik as a subdirectory(/swarmpit), however, I am bumping into a few issues and I am not sure how to solve them.

Traefik can just change the [PathPrefix ](https://docs.traefik.io/routing/routers/#rule)with one caveat, the app has to listen on that path.
> Since the path is forwarded as-is, your service is expected to listen on /products.

Of course, this doesn't work as swarmpit is listening on /. 

Traefik can strip the PathPrefix](https://docs.traefik.io/middlewares/stripprefix/) when forwarding the request to Swarmpit, however, again, there's a caveat.
> If your backend is serving assets (e.g., images or Javascript files), chances are it must return properly constructed relative URLs.

When connecting to <url>/swarmpit, I can see the 404s when it tries loading js, css, etc as it tries pulling those from /_ instead of /_swarmpit and for Traefik those files don't exist there.

Having this option as an environment variable configuration would be amazing but in the meantime, is there any way for me to manually change the path?

**Comment by lukezamboni** [comment]
This seems to be a duplicate of https://github.com/swarmpit/swarmpit/issues/326. My apologies.

It was closed without a solution though and on the latest release I get the following:
![image](https://user-images.githubusercontent.com/16715451/122794646-7a0e2800-d28a-11eb-9fb3-73ec08e49596.png)

My compose:
```
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
      - SWARMPIT_BASE_URL=/swarmpit/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.swarmpit-http.rule=Host(`swarm-node01.etc`) && PathPrefix(`/swarmpit`)
        - traefik.http.routers.swarmpit-http.entrypoints=http
        - traefik.http.routers.swarmpit-http.middlewares=https-redirect
        - traefik.http.routers.swarmpit-https.rule=Host(`swarm-node01.etc`) && PathPrefix(`/swarmpit`)
        - traefik.http.routers.swarmpit-https.entrypoints=https
        - traefik.http.routers.swarmpit-https.tls=true
        - traefik.http.services.swarmpit.loadbalancer.server.port=8080
```

**Comment by nohaapav** [comment]
@lukezamboni I think  `SWARMPIT_BASE_URL` is not longer supported.

**Comment by lukezamboni** [comment]
@nohaapav it looks like it was removed on this [commit](https://github.com/swarmpit/swarmpit/commit/5f94c9fe07f03a7ee446a6cc220baf9ec8162205).

Is there absolutely nothing I can do about it?

**Comment by nohaapav** [comment]
I mean we know about swagger issue behind proxy .. but swarmpit should work just fine

**Comment by lukezamboni** [comment]
I get the swagger issue on the URL https://swarm-node01.url.com/swarmpit/index.html.

**Comment by HedgeShot** [comment]
Hey, 

I am also interested by this. Are we out of luck? Hitting the same issue as you as swarmpit tries to reach the url:
`https://www.url.com/api/swagger.json` instead of `https://www.url.com/swarmpit/api/swagger.json`

**Comment by David-COUDRAY** [comment]
Use StripPrefix Treafik fonction to get Swarmpit on Path.

I've just a problem with API to get Memory and CPU usage

```
version: '3.3'

services:
  web:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net

        - traefik.http.routers.swarmpit-https.rule=Host(`domain.com`) && (PathPrefix(`/swarmpit/`) || Headers(`Referer`, `https://domain.com/swarmpit/`))
        - traefik.http.routers.swarmpit-https.entrypoints=https
        - traefik.http.routers.swarmpit-https.tls=true
        #- traefik.http.routers.swarmpit-https.tls.certresolver=le

        - traefik.http.routers.swarmpit-https.middlewares=swarmpit-stripprefix
        - traefik.http.middlewares.swarmpit-stripprefix.stripprefix.prefixes=/swarmpit

        - traefik.http.services.swarmpit.loadbalancer.server.port=8080

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true

  influxdb:
    image: influxdb:1.7
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
      placement:
        constraints:
          - node.labels.swarmpit.influx-data == true

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true
  traefik-net:
    external: true

volumes:
  db-data:
    driver: local
  influxdb-data:
    driver: local

```
