### ISSUE TITLE
Feature: UI for container labels (not deploy labels) 

### ISSUE THREAD

**Issue by 4n70w4** [swarmpit/swarmpit#622]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

```yaml
version: '3.8'
services:
 
  traefik:
    image: traefik
        labels:
                com.datadoghq.ad.logs: '[{"source": "something", "service": "balancer"}]'

    deploy:
      labels:
        traefik.enable: 'true'
        traefik.dashboard.frontend.rule: Host:{{ traefik_domain }}
        traefik.dashboard.port: 8080
```

I can't edit service labels via UI, only deploy->labels UI presented.

**Additional information (e.g. docker version, cluster setup,...):**

Version: 1.10-37edab1

May be similar https://github.com/swarmpit/swarmpit/issues/364
