### ISSUE TITLE
Swarmpit behind Traefik 2.x for https termination results in Gateway Timeout

### ISSUE THREAD

**Issue by Leopere** [swarmpit/swarmpit#630]
**Description**

**Steps to reproduce the issue:**
1. Launch a single node swarm instance with Traefik as defined in below compose files and a single node instance of Swarmpit
2. Attempt and fail to load page https://swarmpit.example.com 
3. File bug report

**What happens:**
Gateway timeout

**What should happen:**
Load swarmpit over HTTPS from behind reverse proxy.

**Additional information (e.g. docker version, cluster setup,...):**
`docker network create --driver=overlay traefik`
and then run docker stack deploy on both of the stackfiles loosely defined by running this command-ish `docker stack deploy -c [traefik2x.yml|swarmpit.yml] [traefik|swarmpit]`

traefik2x.yml

```yaml
version: "3.7"
services:
########### https://blog.creekorful.org/2020/01/how-to-expose-traefik-2-dashboard-securely-docker-swarm/
  traefik:
    image: traefik:v2.3.4
    command:
      # Docker swarm configuration
#      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.endpoint=http://dockersocket:2375"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      # Configure entrypoint
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # SSL configuration
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=admin@example.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      # Global HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Enable dashboard
      - "--api.dashboard=true"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      # To persist certificates
      - /root/traefik2/conf:/letsencrypt
    networks:
      - traefik
      - docker-socket
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=888" # required by swarm but not used.
        - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.traefik.service=api@internal"
  dockersocket:
    image: tecnativa/docker-socket-proxy
    networks:
      - docker-socket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - NETWORKS=1
      - SERVICES=1
      - TASKS=1

networks:
  traefik:
    external: true
    name: traefik
  docker-socket:
    driver: overlay
    driver_opts:
      encrypted: 'true'
```
swarmpit.yml
```YAML
version: '3.7'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - 888:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - net
    deploy:
      labels:
        ## Traefik 2.x
        - "traefik.enable=true"
        - "traefik.http.routers.swarmpit.tls=true"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
        - "traefik.http.routers.swarmpit.rule=Host(`swarmpit.example.com`)"
        - "traefik.http.routers.swarmpit.entrypoints=websecure"
        - "traefik.http.routers.swarmpit.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.swarmpit.service=swarmpit"
#        - "traefik.http.routers.swarmpit.middlewares=swarmpit-header"
#        - "traefik.http.middlewares.swarmpit-header.headers.customresponseheaders.X-swarmpit-Server-URL=https://swarmpit.example.com/"
        - "traefik.docker.network=traefik"
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M

  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 128M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
  traefik:
    external: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
```

**Comment by kallsbo** [comment]
The configuration seems to be a bit of. Just comparing to my own configuration running swarmpit behind traefik.

Starting with traefik2x.yml:
Remove: - "traefik.http.services.traefik.loadbalancer.server.port=888" # required by swarm but not used.
That's not needed at all.

In swarmpit.yml:
You don't publish any ports since they are commented out. That means that the default port of the container should be used. So change: - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
to: - "traefik.http.services.swarmpit.loadbalancer.server.port=888"

Then it should work.

**Comment by Leopere** [comment]
@kallsbo you're awesome thank you!  Traefik 2.x is so intimidating after the ease of use on 1.7 plus getting something like Swarmpit right is supremely important you really don't want something this powerful exposed improperly.

Just to clarify it should be port 8080 because that's what the app itself exposes internally to the container networking.  It's good to know that the other port definitions are not explicitly necessary unless you need to expose more than one port.

**Comment by kallsbo** [comment]
The default port of swarmpit is 888, that’s the port for the application in
the container. Just double checked mine and looked at the swarmpit
documentation witch states

   - APP_PORT - default to 888

-- 
Skickat från Gmail Mobile -- Med vänlig hälsning Kristofer Källsbo
***@***.*** Tel: +46 768-98 63 50 Privat blogg:
http://www.kallsbo.se Teknik blogg: http://www.hackviking.com (Engelsk)
LinkedIn: http://se.linkedin.com/pub/kristofer-källsbo/18/b9b/921/

**Comment by thoward27** [comment]
I am experiencing issues running the latest version of swarmpit behind traefik with https. For me, it works *intermittently*, which is always confusing. It will load once or twice, allow some simple clicking around, then start timing out on pages, then the whole site goes down. 

If I access the container directly on the machines IP address it loads perfectly. 

Anyone have any tips on how to get this setup working reliably?

<details><summary>Traefik Configuration</summary>

```yaml
version: "3.3"

services:
  traefik:
    image: "traefik:v2.9"
    networks:
      - traefik-external
      - traefik-internal
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=info@tomhoward.codes"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - "/etc/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: "traefik/whoami"
    networks:
      - traefik-external
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.tomhoward.codes`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=myresolver"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik-external:
    external: true
  traefik-internal:
    external: true
```

</details>

<details><summary>Swarmpit Configuration</summary>

```yaml
version: "3.8"

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      SWARMPIT_DB: http://db:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-internal
      - traefik-external
    ports:
      - "888:8080"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.swarmpit.rule=Host(`swarmpit.tomhoward.codes`)"
        - "traefik.http.routers.swarmpit.entrypoints=websecure"
        - "traefik.http.routers.swarmpit.tls.certresolver=myresolver"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - traefik-internal
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - traefik-internal
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 512M

  agent:
    image: swarmpit/agent:latest
    environment:
      DOCKER_API_VERSION: 1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-internal
    deploy:
      mode: global
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

networks:
  traefik-internal:
    external: true
  traefik-external:
    external: true

volumes:
  db-data:
  influx-data:
```

</details>

<details><summary>Traefik Router Screenshot</summary>

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15902840/216779900-0b8f992d-e8d6-4981-a85d-29e6a7da3fa0.png">

</details>
