### ISSUE TITLE
Entrypoint is ignored when editing stack

### ISSUE THREAD

**Issue by Tinekk** [swarmpit/swarmpit#636]
**Description**
Entrypoint is ignored when editing stack

**Steps to reproduce the issue:**
1. Create new stack
```
version: '3.3'
services:
  test:
    image: ubuntu:18.04
    entrypoint:
    - /bin/ps
```
2. Edit recently created stack

**What happens:**
Presented compose file does not contains entrypoint

**What should happen:**
Compose file should contain entrypoint

**Additional information (e.g. docker version, cluster setup,...):**
Swarmpit v1.9
Presented compose file:
```
version: '3.3'
services:
  test:
    image: ubuntu:18.04
    networks:
     - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay
````
