### ISSUE TITLE
Network aliases are taken into accounts but are not visible in edit mode and do not survive a redeploy

### ISSUE THREAD

**Issue by apt-bh** [swarmpit/swarmpit#649]
**Description**

We have two services in the same network and one of them need to communicate with the other using a valid url format. As such, since we cannot use '.' in service name, we want to use the network/aliases system.

When adding that configuration on the service and deploying it, it works as our service can communicate with the other.
However, when editing the stack configuration it seems swarmpit has not taken it into account.

As such, after editing it and/or redeploying the stack, we lose the alias and the services can't communicate anymore.

**Steps to reproduce the issue:**
1. Create two services with an alias defined on service 1 : 
```yml
version: '3.3'
services:
  service1:
    image: registry.com/service1
    networks:
      net:
        aliases:
          - service1.local
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == worker
   
  service2:
    image: registry.com/service2
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == worker
networks:
  net:
    driver: overlay
```

2. After deploying the container service1 is indeed accessible via service1 through 'http://service1.local'.
3. When we want to edit back the stack, here is the saved config ;
```yml
version: '3.3'
services:
  service1:
    image: registry.com/service1
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == worker
   
  service2:
    image: registry.com/service2
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == worker
networks:
  net:
    driver: overlay
```
The alias section has disapeared and redeploying the stack removes the alias since we can't connect anymore to 'http://service1.local'

**What happens:**
We don't have persistence of our network aliases setup

**What should happen:**
We should be able to save the fact that an alias has been defined for a service of our stack

**Additional information (e.g. docker version, cluster setup,...):**
This also affects our aliases when using overlay network to connect multiple stacks.
