### ISSUE TITLE
CouchDB not starting with default parameters

### ISSUE THREAD

**Issue by guanana** [swarmpit/swarmpit#660]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

swarmpit does not start. It seems to be a problem with couchdb container

**Steps to reproduce the issue:**
1. Try to install it
2. Couch DB gets stuck in 137 exit error
3. Increase mem limits on CouchDB and then the app cannot connect

**What happens:**

The app never starts since couch db is NOT available

**What should happen:**

CouchDB should start properly so the app can connect and start using the DB

**Additional information (e.g. docker version, cluster setup,...):**

I solved the problem by adding:
```
  db_couch:
    image: couchdb:2.3.1 <-- I as well updated to latest bug fix version from 2.3.0 to 2.3.1 just in case that made a difference but not
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
 ```
Section separated for clarity on what was added:
```
    ulimits:
      nofile:
        soft: 1000
        hard: 2000
```

```
    deploy:
      resources:
        limits:
          cpus: '0.90' <-- Increased cpu to see if that made a difference... it didn't
          memory: 2048M <-- Increased mem
```
manually on the deployment file. Before that the DB was just hanging and the app unable to connect saying `Connection refused`. Waiting for more than 10% CPU topping up and nothing happened. Change the ulimits for the couchdb container and I get a healthy connection almost immediately.
