### ISSUE TITLE
Support for volume tmpfs in docker compose

### ISSUE THREAD

**Issue by mrq1911** [swarmpit/swarmpit#683]
```
volumes:
- type: tmpfs
   target: /var/cache/nginx
```

**Comment by NeilInnes** [comment]
NFS volumes aren't supported either:

e.g.

```
  storage001_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=storage001.nfs.server.com,rw,nolock,hard,noatime,nodiratime,tcp"
      device: ":/export/NAME/dir"
```
