### ISSUE TITLE
Swarmpit couchdb service need much more memore than specified in limits

### ISSUE THREAD

**Issue by andy-mishechkin** [swarmpit/swarmpit#697]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Swarmpit couchdb service need much more memore than specified in limits in docker compose file**
Hello!
I had a sevral swarmpit deployments before without any issues, using the standart method:
```
git clone https://github.com/swarmpit/swarmpit -b master
docker stack deploy -c swarmpit/docker-compose.yml swarmpit
```
But I've faced with strange issue in my last swarmpit deployment - couch db service was becoming failed aftrer 10-30 sec since creation without any information in task log. After long investigation I've found than service reach out of memory limit, which is specified in Swarmpit docker compose file:
```
  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M 
```
I've commented these limits, and couch db service has been started successfully. I see that couch db service took 1,6 Gb of RAM. Why did it need so much memory in this case ?
Bellow the screenshots with information about nodes and couch db service.

![image](https://github.com/user-attachments/assets/f0fc31d8-02e2-4144-9d66-ace994f6c98c)

**Additional information (e.g. docker version, cluster setup,...):**
Docker version 27.3.1, build ce12230
Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2

Two nodes with the next parameters:
Kernel Version: 6.11.0-9-generic
 Operating System: Ubuntu 24.10
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 61.63GiB
